name: Publish packages to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - name: Install dependencies
        run: uv sync
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish
